### PR TITLE
Fix Cannot read property 'body' of undefined #1

### PR DESCRIPTION
**Pull request by jonadeline**
Fix error in Chrome and Safari.
Still not working in Firefox but this is another issue. 
Couldn't test what's happening in IE and Edge.

### CODE REVIEW

**Comment by garryyao** [comment]
Hi, thanks for the pr, 
`window.currentImport` a shim api provided [in Polymer](https://github.com/Polymer/polycasts/blob/master/ep21-behaviors/behaviors-demo/bower_components/polymer/polymer-micro.html#L87) unless you're not running this with Polymer you shall not get any error.

**Comment by DennisVis** [comment]
I'm getting the same error and definitely am running Polymer (2.0)

**Comment by jonadeline** [comment]
Hi Gary, I confirm I was running it in a Polymer 2 component.

**Comment by garryyao** [comment]
Alright, currentScript is [fully landed](https://caniuse.com/#feat=document-currentscript) on all browsers except for IE11, shall be safe to adapt this PR.

**Pull request merged**
